name: Build
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  SERVICE_NAME: auth
  GOVER: ">=1.20"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |-
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Install Cosign
        if: ${{ github.event_name == 'push' }}
        uses: sigstore/cosign-installer@main
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.branch }} -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.sha_short }}

      - name: Push Docker Image
        if: ${{ github.event_name == 'push' }}
        run: |-
          docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.branch }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.sha_short }}
      - name: Get image digest
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "image_digest_sha=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.sha_short }})" >> $GITHUB_ENV
          echo "image_digest_branch=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.branch }})" >> $GITHUB_ENV
      - name: Sign image
        run: cosign sign --key env://COSIGN_PRIVATE_KEY ${{ env.image_digest_sha }} ${{ env.image_digest_branch }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}  
  deploy-paza:
    name: Update PAZA GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAZA_GITOPS_TOKEN }}
        repository: vpaza/gitops
        path: gitops
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops
        git config user.name "${{ secrets.PAZA_GITOPS_USER }}"
        git config user.email "${{ secrets.PAZA_GITOPS_EMAIL }}"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update deployment
      run: |-
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/overlays/prod
        kustomize edit set image vzanartcc/$SERVICE_NAME=${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$HASH
        git add .
        git commit -m "Update $SERVICE_NAME image"
        git push
  deploy-phzh:
    name: Update PHZH GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAZA_GITOPS_TOKEN }}
        repository: vphzh/gitops
        path: gitops
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops
        git config user.name "${{ secrets.PAZA_GITOPS_USER }}"
        git config user.email "${{ secrets.PAZA_GITOPS_EMAIL }}"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update deployment
      run: |-
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/overlays/prod
        kustomize edit set image vzanartcc/$SERVICE_NAME=${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$HASH
        git add .
        git commit -m "Update $SERVICE_NAME image"
        git push
